name       : xcb-util-image
version    : 0.4.0
release    : 5
source     :
    - http://xcb.freedesktop.org/dist/xcb-util-image-0.4.0.tar.gz : cb2c86190cf6216260b7357a57d9100811bb6f78c24576a3a5bfef6ad3740a42
license    : MIT
component  : xorg.library
summary    : xcb-util extension - image
description: |
    xcb-util extension - image
builddeps  :
    - pkgconfig(xcb-shm)
    - pkgconfig(xproto)
    - pkgconfig(xcb-util)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
