name       : xcb-util-image
version    : 0.4.1
release    : 8
source     :
    - http://xcb.freedesktop.org/dist/xcb-util-image-0.4.1.tar.gz : 0ebd4cf809043fdeb4f980d58cdcf2b527035018924f8c14da76d1c81001293b
license    : MIT
component  : xorg.library
summary    : xcb-util extension - image
description: |
    This library provides an XCB port of Xlib's XImage and XShmImage functions
builddeps  :
    - pkgconfig(xcb-shm)
    - pkgconfig(xproto)
    - pkgconfig(xcb-util)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
